repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.3.2
          - "@prettier/plugin-pug@1.16.5"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.7.0"
    hooks:
      - id: eslint

ci:
  autoupdate_schedule: quarterly
